species:
  saureus: "staphylococcus aureus"
  ecoli: "escherichia coli"
  kpneumoniae: "klebsiella pneumoniae"
  bpertussis: "bordetella pertussis"
  mtuberculosis: "mycobacterium tuberculosis"


mlst_scheme:
  saureus: "saureus"
  ecoli: "ecoli_achtman_4"
  kpneumoniae: "klebsiella"
  bpertussis: "bordetella_3"
  mtuberculosis: "mycobacteria_2"

dsets:
  saureus_ST5:
    species: "saureus"
    strain: "5"
    ref_acc: "GCF_000009665.1"
    threshold: 0.005
  saureus_ST1:
    species: "saureus"
    strain: "1"
    ref_acc: "GCF_002795285.1"
    threshold: 0.005
  ecoli_ST73:
    species: "ecoli"
    strain: "73"
    ref_acc: "GCF_014262945.1"
    threshold: 0.008
  ecoli_ST69:
    species: "ecoli"
    strain: "69"
    ref_acc: "GCA_024662075.1"
    threshold: 0.008
  ecoli_ST95:
    species: "ecoli"
    strain: "95"
    ref_acc: "GCF_008632595.1"
    threshold: 0.008
  kpneumoniae_ST11:
    species: "kpneumoniae"
    strain: "11"
    ref_acc: "GCA_003203435.1"
    threshold: 0.005
  kpneumoniae_ST258:
    species: "kpneumoniae"
    strain: "258"
    ref_acc: "GCA_008121515.1"
    threshold: 0.005
  kpneumoniae_ST15:
    species: "kpneumoniae"
    strain: "15"
    ref_acc: "GCF_025884175.1"
    threshold: 0.005
  kpneumoniae_ST14:
    species: "kpneumoniae"
    strain: "14"
    ref_acc: "GCF_028583665.1"
    threshold: 0.005
  kpneumoniae_ST512:
    species: "kpneumoniae"
    strain: "512"
    ref_acc: "GCF_021485005.1"
    threshold: 0.005
  kpneumoniae_ST17:
    species: "kpneumoniae"
    strain: "17"
    ref_acc: "GCF_037477805.1"
    threshold: 0.005
  bpertussis_ST83:
    species: "bpertussis"
    strain: "83"
    ref_acc: "GCF_004635405.1"
    threshold: 0.001
  mtuberculosis_ST1:
    species: "mtuberculosis"
    strain: "1"
    ref_acc: "GCA_000195955.2"
    threshold: 0.005


metadata:
  - accession
  - assminfo-biosample-accession
  - assminfo-biosample-collection-date
  - assminfo-biosample-geo-loc-name
  - assminfo-biosample-host
  - assminfo-biosample-isolate
  - assminfo-biosample-strain
  - assminfo-biosample-description-comment
  - assminfo-bioproject
  - assminfo-name
  - assminfo-assembly-method
  - assminfo-sequencing-tech
  - assminfo-submitter
  - assmstats-total-number-of-chromosomes
  - assmstats-total-number-of-chromosomes
  - assmstats-total-sequence-len
  - assmstats-contig-l50
  - assmstats-contig-l50
  - assmstats-gc-percent
  - assmstats-genome-coverage
  - annotinfo-featcount-gene-total
  - annotinfo-pipeline
  - annotinfo-provider
  - annotinfo-release-date
  - checkm-completeness
