species:
  ecoli: "escherichia coli"
  saureus: "staphylococcus aureus"
  hpylori: "helicobacter pylori"
  spneumoniae: "streptococcus pneumoniae"
  kpneumoniae: "klebsiella pneumoniae"
  # mtuberculosis: "mycobacterium tuberculosis"
  # bpertussis: "bordetella pertussis"
  # paeruginosa: "pseudomonas aeruginosa"
  # spyogenes: "streptococcus pyogenes"
  # sflexneri: "shigella flexneri"


mlst_scheme:
  saureus: "saureus"
  ecoli: "ecoli_achtman_4"
  kpneumoniae: "klebsiella"
  bpertussis: "bordetella_3"
  mtuberculosis: "mycobacteria_2"
  paeruginosa: "paeruginosa"
  hpylori: "helicobacter"
  spneumoniae: "spneumoniae"
  spyogenes: "spyogenes"
  sflexneri: "ecoli"

metadata:
  - accession
  - assminfo-bioproject
  - assminfo-biosample-accession
  - organism-name
  - organism-infraspecific-strain
  - assminfo-biosample-collection-date
  - assminfo-biosample-geo-loc-name
  - assminfo-biosample-host
  - assminfo-biosample-isolate
  - assminfo-biosample-isolation-source
  - assminfo-biosample-strain
  - assminfo-biosample-description-comment
  - assminfo-name
  - assminfo-assembly-method
  - assminfo-sequencing-tech
  - assminfo-submitter
  - assminfo-release-date
  - assmstats-total-number-of-chromosomes
  - assmstats-number-of-contigs
  - assmstats-total-sequence-len
  - assmstats-contig-n50
  - assmstats-contig-l50
  - assmstats-gc-percent
  - assmstats-genome-coverage
  - annotinfo-featcount-gene-total
  - annotinfo-pipeline
  - annotinfo-provider
  - annotinfo-release-date
  - annotinfo-busco-complete
  - annotinfo-busco-missing
  - checkm-completeness
  - checkm-contamination
